# Generated by Django 5.2.6 on 2025-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
